name: luggage_organizer
description: "Helps to get ready for a trip"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.15.3
  flutter:
    sdk: flutter
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true