name: luggage_organizer
description: "Helps to get ready for a trip"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc_concurrency: ^0.2.3
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  rxdart: ^0.27.7

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcon
      fonts:
        - asset: assets/fonts/AppIcon.ttf
  assets:
    - assets/icons/