// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6id-YIHqeGtiSMX4GSY9sS6c3mtZxB4k',
    appId: '1:5525720513:web:cec8fc9fb3c8a339e6f340',
    messagingSenderId: '5525720513',
    projectId: 'luggage-organizer',
    authDomain: 'luggage-organizer.firebaseapp.com',
    storageBucket: 'luggage-organizer.appspot.com',
    measurementId: 'G-5K9CVL36Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLxkRSQWNb7JVFcb4xJuW9plZZONqor4',
    appId: '1:5525720513:android:b16f045f1fe4c6a2e6f340',
    messagingSenderId: '5525720513',
    projectId: 'luggage-organizer',
    storageBucket: 'luggage-organizer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzcSXGtCipmekP-8KPw2qC-TbEcOd1KbI',
    appId: '1:5525720513:ios:041541aa2133eb5fe6f340',
    messagingSenderId: '5525720513',
    projectId: 'luggage-organizer',
    storageBucket: 'luggage-organizer.appspot.com',
    iosBundleId: 'org.tapo.luggageOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzcSXGtCipmekP-8KPw2qC-TbEcOd1KbI',
    appId: '1:5525720513:ios:488cc8bea1d09df4e6f340',
    messagingSenderId: '5525720513',
    projectId: 'luggage-organizer',
    storageBucket: 'luggage-organizer.appspot.com',
    iosBundleId: 'org.tapo.luggageOrganizer.RunnerTests',
  );
}
